In [1]:
import pandas as pd
import numpy as np

In [2]:
#Reading in data and looking at the number of rows and columns using shape 
x_train = pd.read_csv('x_train.csv')
y_train = pd.read_csv('y_train.csv')
x_test = pd.read_csv('x_test.csv')
y_test = pd.read_csv('y_test.csv')
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1472, 1)
(1472, 1)
(192, 1)
(192, 1)


In [3]:
y_train.head(2)

Pos/Neg_nextday_Change
0                       0
1                       1

In [4]:
x_train.head(2)

Top_Headlines_words
0  apple google poaching settlement appears heade...
1  apple exploring settlement electric car batter...

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
# Converting the x_train and x_test dataframe to list data structure. As TfidfVectorizer doesn't work with dataframe. 
Headlines_Train = x_train['Top_Headlines_words'].tolist()
Headlines_Test = x_test['Top_Headlines_words'].tolist()
Headlines_Train[0:3]

['apple google poaching settlement appears headed approval exclusive obama sharply criticizes china plan new technology rule nasdaq clear 5000 barrier dow hit recordhigh monday nasdaq hit 5000 milestone first time since 2000 samsung unveils sleek new galaxy phone battle apple',
 'apple exploring settlement electric car battery maker apple plan fix next week newly uncovered freak security bug apple edge samsung global smartphone sale gartner bmw ceo see challenge mounting successor exclusive huawei plan big push sell phone wearable device u sharp planning tap bank second bailout three year sharp planning tap bank second bailout three year',
 'hbo talk apple google launch streaming service report report hbo apple near partnership video streaming service judge wary apple claim phone patent harm samsung']

In [7]:
# Setting up the parameters for TfidfVectorizer
tfidf_vec = TfidfVectorizer(max_features = None, max_df = 0.8, min_df = 5, ngram_range = (1,3))

In [8]:
# Fitting the TfidfVectorizer on Train Data
tfidf_vec.fit(Headlines_Train)

TfidfVectorizer(max_df=0.8, min_df=5, ngram_range=(1, 3))

In [9]:
# Transforming Train Fit TfidfVectorizer on on both and x_train and x_test Data.
train_set = tfidf_vec.transform(Headlines_Train)
test_set = tfidf_vec.transform(Headlines_Test)

# Models:

## 1. Random Forest Classifier (RFC)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
# Matrix of 1472 by 3748 is made using TF-IDF
train_set

<1472x3748 sparse matrix of type '<class 'numpy.float64'>'
	with 84436 stored elements in Compressed Sparse Row format>

In [12]:
# Fitting the RandomForest Regression model on Train Data.
RFC = RandomForestClassifier(n_estimators = 100, min_samples_split = 2, min_samples_leaf = 5, max_features = 'sqrt', max_depth = 10, random_state = 42)
RFC.fit(train_set, y_train['Pos/Neg_nextday_Change'])

RandomForestClassifier(max_depth=10, max_features='sqrt', min_samples_leaf=5,
                       random_state=42)

In [13]:
# R Sqaure of model on both Train and Test sets.
print("Random Forest Classifier")
print("R-Sqaure")
print(" ")
print("R-Sqaure on Train Set = "+str(np.round(RFC.score(train_set, y_train), 2)))
print(" ")
print("R-Sqaure on Test Set = "+str(np.round(RFC.score(test_set, y_test), 2)))
print(" ")

Random Forest Classifier
R-Sqaure
 
R-Sqaure on Train Set = 0.68
 
R-Sqaure on Test Set = 0.61
 


In [14]:
newz = 'wikileaks say release file cia cyber spying tool'

In [15]:
pred = RFC.predict(tfidf_vec.transform([newz]))
pred

array([1], dtype=int64)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf_model = DecisionTreeClassifier(criterion="gini", random_state=45,max_depth=10, min_samples_leaf=2)   
clf_model.fit(X_train_scaled,Y_train)

In [55]:
Newz_Senti.__dict__

mappingproxy({'__config__': __main__.Config,
              '__fields__': {'Newz_Headline': ModelField(name='Newz_Headline', type=str, required=True)},
              '__exclude_fields__': None,
              '__include_fields__': None,
              '__validators__': {},
              '__pre_root_validators__': [],
              '__post_root_validators__': [],
              '__schema_cache__': {},
              '__json_encoder__': <staticmethod at 0x11b4cdec2b0>,
              '__custom_root_type__': False,
              '__private_attributes__': {},
              '__slots__': set(),
              '__hash__': None,
              '__class_vars__': set(),
              '__module__': '__main__',
              '__annotations__': {'Newz_Headline': str},
              '__doc__': None,
              '__abstractmethods__': frozenset(),
              '_abc_impl': <_abc._abc_data at 0x11b4cdfcf80>,
              '__signature__': <pydantic.utils.ClassAttribute at 0x11b4cdecd00>})

#### RFC is overfitting

In [93]:
# Checking Accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [29]:
predictions_rfc = RFC.predict(test_set)

In [30]:
matrix = confusion_matrix(y_test, predictions_rfc)
print(matrix)

[[ 13  73]
 [  1 105]]


In [31]:
acc_score = accuracy_score(y_test, predictions_rfc)
print(np.round(acc_score, 2))

0.61


In [32]:
report = classification_report(y_test, predictions_rfc)
print(report)

              precision    recall  f1-score   support

           0       0.93      0.15      0.26        86
           1       0.59      0.99      0.74       106

    accuracy                           0.61       192
   macro avg       0.76      0.57      0.50       192
weighted avg       0.74      0.61      0.52       192



#### RFC Accuracy is 59%

## 2. Naive Bayes

In [88]:
from sklearn.naive_bayes import MultinomialNB

In [89]:
MNB = MultinomialNB()
MNB.fit(train_set, y_train['Pos/Neg_nextday_Change'])

MultinomialNB()

In [90]:
# R Sqaure of model on both Train and Test sets.
print("Multinomial Naive Bayes")
print("R-Sqaure")
print(" ")
print("R-Sqaure on Train Set = "+str(np.round(RFC.score(train_set, y_train), 2)))
print(" ")
print("R-Sqaure on Test Set = "+str(np.round(RFC.score(test_set, y_test), 2)))
print(" ")

Multinomial Naive Bayes
R-Sqaure
 
R-Sqaure on Train Set = 0.68
 
R-Sqaure on Test Set = 0.61
 


In [158]:
newz = 'ios'

In [159]:
pred = MNB.predict(tfidf_vec.transform([newz]))
pred

array([1], dtype=int64)

In [160]:
pred = RFC.predict(tfidf_vec.transform([newz]))
pred

array([1], dtype=int64)

In [91]:
predictions_mnb = MNB.predict(test_set)

In [94]:
matrix = confusion_matrix(y_test, predictions_mnb)
print(matrix)

[[17 69]
 [ 9 97]]


In [38]:
acc_score = accuracy_score(y_test, predictions_mnb)
print(np.round(acc_score, 2))

0.59


In [39]:
report = classification_report(y_test, predictions_mnb)
print(report)

              precision    recall  f1-score   support

           0       0.65      0.20      0.30        86
           1       0.58      0.92      0.71       106

    accuracy                           0.59       192
   macro avg       0.62      0.56      0.51       192
weighted avg       0.62      0.59      0.53       192



In [40]:
from sklearn.ensemble import GradientBoostingClassifier

In [41]:
GBoost = GradientBoostingClassifier()
GBoost.fit(train_set, y_train['Pos/Neg_nextday_Change'])

GradientBoostingClassifier()

In [42]:
# R Sqaure of model on both Train and Test sets.
print("Multinomial Naive Bayes")
print("R-Sqaure")
print(" ")
print("R-Sqaure on Train Set = "+str(np.round(GBoost.score(train_set, y_train), 2)))
print(" ")
print("R-Sqaure on Test Set = "+str(np.round(GBoost.score(test_set, y_test), 2)))
print(" ")

Multinomial Naive Bayes
R-Sqaure
 
R-Sqaure on Train Set = 0.87
 
R-Sqaure on Test Set = 0.56
 
